### ISSUE TITLE
Deintigrate the Drive Systems

### ISSUE THREAD

**Issue by 66945** [Team4388/Robot-Essentials#32]
I like them

They must not be stopped

**Comment by C4llSqin** [comment]
bit of a scuffed pull request, my bad

**Comment by 66945** [comment]
I just want to fully decouple the robot base from any specific drive system now that we use more than one.
Basically just a code cleanup which we could have a new member do.

**Comment by C4llSqin** [comment]
>  Basically just a code cleanup which we could have a new member do.

Then why did you assign me?
